import {
  Key,
  Link,
  MapPin,
  FileText,
  Database,
  Code,
  Hash,
  Clock,
  FileDiff,
  Type,
  Image as ImageIcon,
  QrCode,
  Mail,
  Landmark,
  Car,
  CreditCard,
  Users,
  Vote,
  Scroll,
  Building2,
  Calculator,
  Shield,
  Binary,
  MessageSquare,
  FileCode,
} from "lucide-react"

export type ToolCategory = "Geral" | "Desenvolvedor" | "Texto e Mídia"

export type Tool = {
  id: string
  name: string
  description: string
  icon: React.ElementType
  path: string
  category: ToolCategory
}

export const tools: Tool[] = [
  // Geral
  {
    id: "gerador-senha",
    name: "Gerador de Senha",
    description: "Crie senhas fortes e seguras com opções personalizáveis.",
    icon: Key,
    path: "/tools/password-generator",
    category: "Geral",
  },
  {
    id: "encurtador-url",
    name: "Encurtador de URL",
    description: "Encurte links longos para compartilhar mais facilmente.",
    icon: Link,
    path: "/tools/url-shortener",
    category: "Geral",
  },
  {
    id: "dados-brasil",
    name: "Dados Brasil",
    description: "Consulte informações sobre CEP, DDD, etc.",
    icon: MapPin,
    path: "/tools/brazil-data",
    category: "Geral",
  },
  {
    id: "gerador-cpf-cnpj",
    name: "Gerador CPF/CNPJ",
    description: "Gere e valide CPFs e CNPJs para testes de software.",
    icon: FileText,
    path: "/tools/cpf-cnpj-generator",
    category: "Geral",
  },
  {
    id: "gerador-conta-bancaria",
    name: "Gerador de Conta Bancária",
    description: "Gere números de agência e conta bancária para testes de software.",
    icon: Landmark,
    path: "/tools/bank-account-generator",
    category: "Geral",
  },
  {
    id: "gerador-pis-pasep",
    name: "Gerador de PIS/PASEP",
    description: "Gere e valide números de PIS/PASEP para testes de software.",
    icon: FileText,
    path: "/tools/pis-pasep-generator",
    category: "Geral",
  },
  {
    id: "gerador-veiculos",
    name: "Gerador de Veículos e Placas",
    description: "Gere dados de veículos fictícios com placa, Renavam e chassi válidos.",
    icon: Car,
    path: "/tools/vehicle-generator",
    category: "Geral",
  },
  {
    id: "gerador-curriculo",
    name: "Gerador de Currículo",
    description: "Crie e formate seu currículo profissional rapidamente e exporte para PDF.",
    icon: FileText,
    path: "/tools/resume-builder",
    category: "Geral",
  },
  {
    id: "gerador-cartao-credito",
    name: "Gerador de Cartão de Crédito",
    description: "Gere e valide números de cartão de crédito de diversas bandeiras.",
    icon: CreditCard,
    path: "/tools/credit-card-generator",
    category: "Geral",
  },
  {
    id: "gerador-pessoas",
    name: "Gerador de Pessoas",
    description: "Gere dados completos de pessoas (RG, CPF, CEP, Endereço, etc).",
    icon: Users,
    path: "/tools/person-generator",
    category: "Geral",
  },
  {
    id: "gerador-cnh",
    name: "Gerador de CNH",
    description: "Gere e valide números de Carteira Nacional de Habilitação (CNH).",
    icon: Car,
    path: "/tools/cnh-generator",
    category: "Geral",
  },
  {
    id: "gerador-titulo-eleitor",
    name: "Gerador de Título de Eleitor",
    description: "Gere e valide números de Título de Eleitor por estado (UF).",
    icon: Vote,
    path: "/tools/voter-title-generator",
    category: "Geral",
  },
  {
    id: "gerador-certidao",
    name: "Gerador de Certidão",
    description: "Gere e valide certidões de Nascimento, Casamento e Óbito (CNJ).",
    icon: Scroll,
    path: "/tools/certificate-generator",
    category: "Geral",
  },
  {
    id: "gerador-inscricao-estadual",
    name: "Gerador de Inscrição Estadual",
    description: "Gere e valide números de Inscrição Estadual para empresas de diversos estados.",
    icon: Building2,
    path: "/tools/inscricao-estadual-generator",
    category: "Geral",
  },
  {
    id: "calculadora-salario-liquido",
    name: "Calculadora de Salário CLT",
    description: "Calcule o salário líquido a partir do bruto com descontos de INSS e IRRF.",
    icon: Calculator,
    path: "/tools/salary-calculator",
    category: "Geral",
  },
  {
    id: "gerador-link-whatsapp",
    name: "Gerador de Link do WhatsApp",
    description: "Crie links diretos e QR Codes para iniciar conversas no WhatsApp com mensagens personalizadas.",
    icon: MessageSquare,
    path: "/tools/whatsapp-link-generator",
    category: "Geral",
  },
  {
    id: "dados-fake",
    name: "Dados Fake (BR)",
    description: "Gere dados fictícios brasileiros para testes.",
    icon: Database,
    path: "/tools/fake-data",
    category: "Geral",
  },

  // Desenvolvedor
  {
    id: "formatador-json",
    name: "Formatador JSON",
    description: "Formate, valide e embeleze seus arquivos JSON.",
    icon: Code,
    path: "/tools/json-formatter",
    category: "Desenvolvedor",
  },
  {
    id: "formatador-sql",
    name: "Formatador SQL",
    description: "Formate, embeleze e idente suas consultas SQL de diferentes bancos.",
    icon: Database,
    path: "/tools/sql-formatter",
    category: "Desenvolvedor",
  },
  {
    id: "exemplos-hello-world",
    name: "Exemplos de Código (Hello World)",
    description: "Exemplos de código e sintaxe de inicialização para diversas linguagens de programação.",
    icon: FileCode,
    path: "/tools/hello-world",
    category: "Desenvolvedor",
  },
  {
    id: "gerador-uuid",
    name: "Gerador de UUID",
    description: "Gere Identificadores Únicos Universais (UUIDs).",
    icon: Hash,
    path: "/tools/uuid-generator",
    category: "Desenvolvedor",
  },
  {
    id: "gerador-hash",
    name: "Gerador de Hash",
    description: "Calcule hashes MD5, SHA-1, SHA-256 e mais.",
    icon: Hash,
    path: "/tools/hash-generator",
    category: "Desenvolvedor",
  },
  {
    id: "timestamp-converter",
    name: "Timestamp Converter",
    description: "Converta timestamps Unix para datas legíveis e vice-versa.",
    icon: Clock,
    path: "/tools/timestamp-converter",
    category: "Desenvolvedor",
  },
  {
    id: "diff-checker",
    name: "Diff Checker",
    description: "Compare dois blocos de texto para encontrar as diferenças.",
    icon: FileDiff,
    path: "/tools/diff-checker",
    category: "Desenvolvedor",
  },
  {
    id: "validador-jwt",
    name: "Decodificador e Validador de JWT",
    description: "Decodifique e valide seus JSON Web Tokens (JWT) localmente de forma segura.",
    icon: Shield,
    path: "/tools/jwt-validator",
    category: "Desenvolvedor",
  },
  {
    id: "conversor-base",
    name: "Conversor de Base",
    description: "Converta textos e valores numéricos entre diferentes bases e codificações em tempo real.",
    icon: Binary,
    path: "/tools/base-converter",
    category: "Desenvolvedor",
  },
  {
    id: "conversor-formatos",
    name: "Conversor de Formatos",
    description: "Converta dados facilmente entre JSON, YAML, XML e CSV com validação instantânea.",
    icon: FileCode,
    path: "/tools/format-converter",
    category: "Desenvolvedor",
  },

  // Texto e Mídia
  {
    id: "conversor-texto",
    name: "Conversor de Texto",
    description: "Converta texto para maiúsculas, minúsculas, camelCase, etc.",
    icon: Type,
    path: "/tools/text-converter",
    category: "Texto e Mídia",
  },
  {
    id: "conversor-imagem",
    name: "Conversor de Imagem",
    description: "Converta imagens entre formatos (PNG, JPEG, WebP).",
    icon: ImageIcon,
    path: "/tools/image-converter",
    category: "Texto e Mídia",
  },
  {
    id: "gerador-qrcode",
    name: "Gerador de QR Code",
    description: "Crie códigos QR para links, textos, ou contatos.",
    icon: QrCode,
    path: "/tools/qr-generator",
    category: "Texto e Mídia",
  },
  {
    id: "lorem-ipsum",
    name: "Lorem Ipsum",
    description: "Gere textos de preenchimento para layouts e protótipos.",
    icon: FileText,
    path: "/tools/lorem-ipsum",
    category: "Texto e Mídia",
  },
  {
    id: "validador-email",
    name: "Validador de E-mail",
    description: "Verifique a validade e a sintaxe de endereços de e-mail.",
    icon: Mail,
    path: "/tools/email-validator",
    category: "Texto e Mídia",
  },
]

export const categories: ToolCategory[] = [
  "Geral",
  "Desenvolvedor",
  "Texto e Mídia",
]
